spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:benchmark;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  main:
    banner-mode: off
  data:
    rest:
      base-path: /api
      default-page-size: 20
      max-page-size: 200
      return-body-on-create: true
      return-body-on-update: true
      default-media-type: application/json
      use-hal-as-default-json-media-type: false
server:
  port: ${SERVER_PORT:8083}
  error:
    include-message: always

